// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_locations_slug_730658f7

const RouteID = "r_locations__slug_730658f7"

type Props struct {
	Canonical     string   `json:"canonical"`
	Description   string   `json:"description"`
	Hours         []string `json:"hours"`
	Locality      string   `json:"locality"`
	MapHref       string   `json:"mapHref"`
	Name          string   `json:"name"`
	Phone         string   `json:"phone"`
	PhoneHref     string   `json:"phoneHref"`
	PostalCode    string   `json:"postalCode"`
	Region        string   `json:"region"`
	StreetAddress string   `json:"streetAddress"`
}
