// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_products_slug_3e2e8eb9

const RouteID = "r_products__slug_3e2e8eb9"

type Props struct {
	Availability PropsAvailability `json:"availability"`
	Canonical    string            `json:"canonical"`
	Currency     string            `json:"currency"`
	Description  string            `json:"description"`
	Image        string            `json:"image"`
	ImageAlt     string            `json:"imageAlt"`
	Name         string            `json:"name"`
	Price        float64           `json:"price"`
	PriceLabel   string            `json:"priceLabel"`
	Slug         string            `json:"slug"`
}

type PropsAvailability string

const (
	PropsAvailabilityInStock    PropsAvailability = "InStock"
	PropsAvailabilityOutOfStock PropsAvailability = "OutOfStock"
)
