// Code generated by GoBeyond from page.go. DO NOT EDIT.
import { definePage, schema } from "@go-beyond/schema";

export const page = definePage({
  props: schema.object({
    canonical: schema.string(),
    currentPage: schema.integer(),
    items: schema.array(schema.object({
      href: schema.string(),
      name: schema.string(),
      summary: schema.string()
    })),
    nextHref: schema.optional(schema.string()),
    previousHref: schema.optional(schema.string())
  }),
});
