// Code generated by GoBeyond from page.go. DO NOT EDIT.
import { definePage, schema } from "@go-beyond/schema";

export const page = definePage({
  props: schema.object({
    alternateEnglish: schema.string(),
    alternateFrench: schema.string(),
    authorName: schema.string(),
    canonical: schema.string(),
    description: schema.string(),
    paragraphs: schema.array(schema.string()),
    publishedAt: schema.datetime(),
    publishedLabel: schema.string(),
    slug: schema.string(),
    socialImage: schema.string(),
    title: schema.string()
  }),
});
