// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_route_8a5edab2

const RouteID = "r_route_8a5edab2"

type Props struct {
	FeaturedArticleHref string `json:"featuredArticleHref"`
	FeaturedProductHref string `json:"featuredProductHref"`
}
