// Code generated by GoBeyond from page.go. DO NOT EDIT.
import { definePage, schema } from "@go-beyond/schema";

export const page = definePage({
  props: schema.object({
    displayName: schema.string()
  }),
});
