package codegen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// GeneratePageSchema projects the authored Go Props type into the TypeScript
// contract consumed by the portable React compiler. The Go page package is the
// source of truth; the returned page.schema.ts is generated and must not be
// edited by application teams.
//
// Imported application structs are followed when their import path is below
// modulePath. This deliberately refuses arbitrary external types: a page
// payload must have a visible, JSON-safe shape at the Go/browser boundary.
func GeneratePageSchema(pageFile, moduleRoot, modulePath string) ([]byte, error) {
	resolver := goSchemaResolver{
		moduleRoot: moduleRoot,
		modulePath: strings.TrimSuffix(modulePath, "/"),
		packages:   map[string]*goSchemaPackage{},
		visiting:   map[string]bool{},
	}
	pkg, err := resolver.loadPackage(filepath.Dir(pageFile))
	if err != nil {
		return nil, err
	}
	props, ok := pkg.types["Props"]
	if !ok {
		return nil, fmt.Errorf("%s must declare type Props struct { ... }", pageFile)
	}
	shape, err := resolver.expression(pkg, props.Type)
	if err != nil {
		return nil, fmt.Errorf("generate schema for %s Props: %w", pageFile, err)
	}
	if !strings.HasPrefix(shape, "schema.object(") {
		return nil, fmt.Errorf("%s Props must be a struct", pageFile)
	}
	config, err := parsePageConfig(pkg)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", pageFile, err)
	}
	var source strings.Builder
	source.WriteString("// Code generated by GoBeyond from page.go. DO NOT EDIT.\n")
	source.WriteString("import { definePage, schema } from \"@go-beyond/schema\";\n\n")
	source.WriteString("export const page = definePage({\n")
	if config.revalidate > 0 {
		source.WriteString("  revalidate: " + strconv.Itoa(config.revalidate) + ",\n")
	}
	if len(config.tags) > 0 {
		source.WriteString("  tags: [" + quoteStrings(config.tags) + "],\n")
	}
	source.WriteString("  props: " + indentSchema(shape, "  ") + ",\n")
	source.WriteString("});\n")
	return []byte(source.String()), nil
}

type pageSchemaConfig struct {
	revalidate int
	tags       []string
}

func parsePageConfig(pkg *goSchemaPackage) (pageSchemaConfig, error) {
	var config pageSchemaConfig
	declaration, exists := pkg.values["Config"]
	if !exists {
		return config, nil
	}
	literal, ok := declaration.Values[0].(*ast.CompositeLit)
	if !ok {
		return config, fmt.Errorf("Config must be a gb.PageConfig literal")
	}
	for _, item := range literal.Elts {
		field, ok := item.(*ast.KeyValueExpr)
		if !ok {
			return config, fmt.Errorf("Config must use named fields")
		}
		name, _ := field.Key.(*ast.Ident)
		if name == nil {
			return config, fmt.Errorf("Config contains an invalid field")
		}
		switch name.Name {
		case "Revalidate":
			value, ok := field.Value.(*ast.BasicLit)
			if !ok || value.Kind != token.INT {
				return config, fmt.Errorf("Config.Revalidate must be a whole-number literal")
			}
			seconds, err := strconv.Atoi(value.Value)
			if err != nil || seconds < 0 {
				return config, fmt.Errorf("Config.Revalidate must be non-negative")
			}
			config.revalidate = seconds
		case "Tags":
			values, ok := field.Value.(*ast.CompositeLit)
			if !ok {
				return config, fmt.Errorf("Config.Tags must be a string literal slice")
			}
			for _, value := range values.Elts {
				text, ok := value.(*ast.BasicLit)
				if !ok || text.Kind != token.STRING {
					return config, fmt.Errorf("Config.Tags must contain string literals")
				}
				decoded, err := strconv.Unquote(text.Value)
				if err != nil || decoded == "" {
					return config, fmt.Errorf("Config.Tags must contain non-empty strings")
				}
				config.tags = append(config.tags, decoded)
			}
		}
	}
	if len(config.tags) > 0 && config.revalidate == 0 {
		return config, fmt.Errorf("Config.Tags requires Config.Revalidate")
	}
	return config, nil
}

type goSchemaPackage struct {
	dir     string
	imports map[string]string
	types   map[string]*ast.TypeSpec
	values  map[string]*ast.ValueSpec
}

type goSchemaResolver struct {
	moduleRoot string
	modulePath string
	packages   map[string]*goSchemaPackage
	visiting   map[string]bool
}

func (r *goSchemaResolver) loadPackage(dir string) (*goSchemaPackage, error) {
	dir = filepath.Clean(dir)
	if loaded := r.packages[dir]; loaded != nil {
		return loaded, nil
	}
	parsed, err := parser.ParseDir(token.NewFileSet(), dir, func(info os.FileInfo) bool {
		return strings.HasSuffix(info.Name(), ".go") && info.Name() != "page.schema.go" && !strings.HasSuffix(info.Name(), "_test.go") && !strings.HasSuffix(info.Name(), ".gobeyond_gen.go")
	}, 0)
	if err != nil {
		return nil, err
	}
	if len(parsed) != 1 {
		return nil, fmt.Errorf("expected one Go package in %s", dir)
	}
	pkg := &goSchemaPackage{dir: dir, imports: map[string]string{}, types: map[string]*ast.TypeSpec{}, values: map[string]*ast.ValueSpec{}}
	for _, astPackage := range parsed {
		for _, file := range astPackage.Files {
			for _, importSpec := range file.Imports {
				importPath, err := strconv.Unquote(importSpec.Path.Value)
				if err != nil {
					return nil, err
				}
				name := filepath.Base(importPath)
				if importSpec.Name != nil {
					name = importSpec.Name.Name
				}
				pkg.imports[name] = importPath
			}
			for _, declaration := range file.Decls {
				general, ok := declaration.(*ast.GenDecl)
				if !ok {
					continue
				}
				for _, spec := range general.Specs {
					switch node := spec.(type) {
					case *ast.TypeSpec:
						pkg.types[node.Name.Name] = node
					case *ast.ValueSpec:
						for _, name := range node.Names {
							pkg.values[name.Name] = node
						}
					}
				}
			}
		}
	}
	r.packages[dir] = pkg
	return pkg, nil
}

func (r *goSchemaResolver) expression(pkg *goSchemaPackage, expression ast.Expr) (string, error) {
	switch node := expression.(type) {
	case *ast.Ident:
		switch node.Name {
		case "string":
			return "schema.string()", nil
		case "bool":
			return "schema.boolean()", nil
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64":
			return "schema.integer()", nil
		case "float32", "float64":
			return "schema.number()", nil
		}
		definition, exists := pkg.types[node.Name]
		if !exists {
			return "", fmt.Errorf("unsupported Go type %s", node.Name)
		}
		key := pkg.dir + ":" + node.Name
		if r.visiting[key] {
			return "", fmt.Errorf("recursive Go type %s is not JSON-schema representable", node.Name)
		}
		r.visiting[key] = true
		defer delete(r.visiting, key)
		return r.expression(pkg, definition.Type)
	case *ast.StructType:
		fields := make([]string, 0, len(node.Fields.List))
		for _, field := range node.Fields.List {
			if len(field.Names) != 1 {
				return "", fmt.Errorf("embedded and unnamed fields are not supported")
			}
			name := jsonFieldName(field)
			if name == "-" {
				continue
			}
			fieldType := field.Type
			optional := false
			if pointer, isPointer := field.Type.(*ast.StarExpr); isPointer && jsonOmitEmpty(field) {
				fieldType = pointer.X
				optional = true
			}
			value, err := r.expression(pkg, fieldType)
			if err != nil {
				return "", err
			}
			if optional {
				value = "schema.optional(" + value + ")"
			}
			fields = append(fields, name+": "+value)
		}
		return "schema.object({" + strings.Join(fields, ", ") + "})", nil
	case *ast.ArrayType:
		item, err := r.expression(pkg, node.Elt)
		if err != nil {
			return "", err
		}
		return "schema.array(" + item + ")", nil
	case *ast.StarExpr:
		inner, err := r.expression(pkg, node.X)
		if err != nil {
			return "", err
		}
		return "schema.nullable(" + inner + ")", nil
	case *ast.SelectorExpr:
		qualifier, ok := node.X.(*ast.Ident)
		if !ok {
			return "", fmt.Errorf("unsupported selector type")
		}
		importPath := pkg.imports[qualifier.Name]
		if importPath == "time" && node.Sel.Name == "Time" {
			return "schema.datetime()", nil
		}
		if !strings.HasPrefix(importPath, r.modulePath+"/") {
			return "", fmt.Errorf("%s.%s is external; expose a local JSON DTO instead", qualifier.Name, node.Sel.Name)
		}
		relative := strings.TrimPrefix(importPath, r.modulePath+"/")
		imported, err := r.loadPackage(filepath.Join(r.moduleRoot, filepath.FromSlash(relative)))
		if err != nil {
			return "", err
		}
		return r.expression(imported, ast.NewIdent(node.Sel.Name))
	default:
		return "", fmt.Errorf("unsupported Go type expression %T", expression)
	}
}

func jsonFieldName(field *ast.Field) string {
	name := field.Names[0].Name
	if field.Tag == nil {
		return name
	}
	tag, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return name
	}
	for _, item := range strings.Split(tag, " ") {
		if !strings.HasPrefix(item, "json:") {
			continue
		}
		value, err := strconv.Unquote(strings.TrimPrefix(item, "json:"))
		if err != nil {
			return name
		}
		return strings.Split(value, ",")[0]
	}
	return name
}

func jsonOmitEmpty(field *ast.Field) bool {
	if field.Tag == nil {
		return false
	}
	tag, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return false
	}
	for _, item := range strings.Split(tag, " ") {
		if !strings.HasPrefix(item, "json:") {
			continue
		}
		value, err := strconv.Unquote(strings.TrimPrefix(item, "json:"))
		if err != nil {
			return false
		}
		for _, option := range strings.Split(value, ",")[1:] {
			if option == "omitempty" {
				return true
			}
		}
	}
	return false
}

func quoteStrings(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	return strings.Join(quoted, ", ")
}

func indentSchema(value, prefix string) string {
	value = strings.ReplaceAll(value, ", ", ",")
	var formatted strings.Builder
	indent := 0
	lineStart := false
	writeIndent := func() {
		if !lineStart {
			return
		}
		formatted.WriteString(prefix)
		formatted.WriteString(strings.Repeat("  ", indent))
		lineStart = false
	}
	for _, character := range value {
		switch character {
		case '{':
			writeIndent()
			formatted.WriteString("{\n")
			indent++
			lineStart = true
		case '}':
			indent--
			if !lineStart {
				formatted.WriteByte('\n')
			}
			lineStart = true
			writeIndent()
			formatted.WriteByte('}')
		case ',':
			writeIndent()
			formatted.WriteString(",\n")
			lineStart = true
		case ' ':
			writeIndent()
			formatted.WriteByte(' ')
		default:
			writeIndent()
			formatted.WriteRune(character)
		}
	}
	return formatted.String()
}
