// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_en_articles_slug_2da8a82a

import (
	"time"
)

const RouteID = "r_en_articles__slug_2da8a82a"

type Props struct {
	AlternateEnglish string    `json:"alternateEnglish"`
	AlternateFrench  string    `json:"alternateFrench"`
	AuthorName       string    `json:"authorName"`
	Canonical        string    `json:"canonical"`
	Description      string    `json:"description"`
	Paragraphs       []string  `json:"paragraphs"`
	PublishedAt      time.Time `json:"publishedAt"`
	PublishedLabel   string    `json:"publishedLabel"`
	Slug             string    `json:"slug"`
	SocialImage      string    `json:"socialImage"`
	Title            string    `json:"title"`
}

// Revalidate is how long the origin may reuse this route's computed props,
// from definePage({ revalidate }). Zero leaves the route uncached. It is not
// an HTTP directive: the edge Cache-Control stays the loader's gb.CachePolicy,
// which should be derived from this window rather than drifting from it.
const Revalidate = 0 * time.Second

// Tags are this route's invalidation handles, from definePage({ tags }).
// cache.RevalidateTag on any of them drops the route's cached props.
var Tags []string
