// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_products_slug_3e2e8eb9_add_to_cart

import (
	"encoding/json"
	gb "github.com/Origens-Dev/gobeyond"
	"github.com/Origens-Dev/gobeyond/codegen"
	gbruntime "github.com/Origens-Dev/gobeyond/runtime"
)

const ActionID = "r_products__slug_3e2e8eb9:addToCart"

type Input struct {
	ProductSlug string `json:"productSlug"`
	Quantity    int64  `json:"quantity"`
}

type Output struct {
	CartItemCount int64 `json:"cartItemCount"`
	Saved         bool  `json:"saved"`
}

var inputContract = codegen.Value{Kind: codegen.KindObject, Shape: map[string]codegen.Value{"productSlug": codegen.Value{Kind: codegen.KindString}, "quantity": codegen.Value{Kind: codegen.KindInteger}}}

var outputContract = codegen.Value{Kind: codegen.KindObject, Shape: map[string]codegen.Value{"cartItemCount": codegen.Value{Kind: codegen.KindInteger}, "saved": codegen.Value{Kind: codegen.KindBoolean}}}

func DecodeInput(raw json.RawMessage) (Input, error) {
	var input Input
	if err := codegen.DecodeJSON(inputContract, raw, &input); err != nil {
		return Input{}, err
	}
	return input, nil
}

func ValidateOutput(output Output) error {
	return codegen.ValidateEncodedValue(outputContract, output)
}

func Register(handler func(*gb.ActionContext, Input) (Output, error)) gbruntime.Action {
	return gbruntime.RegisterAction(ActionID, DecodeInput, ValidateOutput, handler)
}
