package project

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const generatedSourceMarker = "// Code generated by gobeyond route projection; DO NOT EDIT."
const generatedModuleMarker = "// Code generated by gobeyond route tooling; DO NOT EDIT."

// SyncGoSources projects route-owned Go into import-safe generated packages.
// Authored app directories remain editor inputs and are never imported by the
// production server.
func SyncGoSources(root string, routes []Route, check bool) error {
	moduleRoot, modulePath, goVersion, err := findModule(root)
	if err != nil {
		return err
	}
	outputs := make(map[string][]byte)
	moduleOutputs := make(map[string][]byte)
	generatedRoot := filepath.Join(root, "internal", "gobeyondgen")
	routeTree := filepath.Join(generatedRoot, "routes")
	apiTree := filepath.Join(generatedRoot, "api")

	websiteRelative, err := filepath.Rel(moduleRoot, root)
	if err != nil || websiteRelative == ".." || strings.HasPrefix(websiteRelative, ".."+string(filepath.Separator)) {
		return errors.New("website root must be inside the Go module root")
	}
	websiteImport := modulePath
	if websiteRelative != "." {
		websiteImport = path.Join(modulePath, filepath.ToSlash(websiteRelative))
	}
	for _, route := range routes {
		authorDir := filepath.Dir(filepath.FromSlash(route.PageFile))
		moduleFile := filepath.Join(authorDir, "go.mod")
		moduleOutputs[moduleFile], err = routeModule(moduleRoot, modulePath, websiteImport, goVersion, authorDir, route.ID)
		if err != nil {
			return err
		}
		packageName := ""
		for _, name := range []string{"page.go", "actions.go"} {
			authorFile := filepath.Join(authorDir, name)
			content, readErr := os.ReadFile(authorFile)
			if errors.Is(readErr, os.ErrNotExist) {
				continue
			}
			if readErr != nil {
				return readErr
			}
			parsed, parseErr := parseRouteSource(root, authorFile, content, websiteImport)
			if parseErr != nil {
				return parseErr
			}
			if packageName != "" && packageName != parsed.Name.Name {
				return fmt.Errorf("route %s mixes Go packages %q and %q; page.go and actions.go must share one package", route.Pattern, packageName, parsed.Name.Name)
			}
			packageName = parsed.Name.Name
			target := filepath.Join(routeTree, route.ID, name)
			outputs[target], err = projectedSource(root, authorFile, content)
			if err != nil {
				return err
			}
		}
	}

	apiRoot := filepath.Join(root, "app", "api")
	err = filepath.WalkDir(apiRoot, func(file string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			if errors.Is(walkErr, os.ErrNotExist) {
				return nil
			}
			return walkErr
		}
		if entry.IsDir() || entry.Name() != "route.go" {
			return nil
		}
		authorDir := filepath.Dir(file)
		relative, relErr := filepath.Rel(apiRoot, authorDir)
		if relErr != nil {
			return relErr
		}
		key := APIKey(relative)
		moduleFile := filepath.Join(authorDir, "go.mod")
		moduleOutputs[moduleFile], relErr = routeModule(moduleRoot, modulePath, websiteImport, goVersion, authorDir, key)
		if relErr != nil {
			return relErr
		}
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		if _, parseErr := parseRouteSource(root, file, content, websiteImport); parseErr != nil {
			return parseErr
		}
		outputs[filepath.Join(apiTree, key, "route.go")], relErr = projectedSource(root, file, content)
		return relErr
	})
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}

	// Projections and route-local modules are ignored, ephemeral build/tooling
	// inputs. Even --check must materialize them in a clean clone before the
	// committed registry and contracts are checked.
	if err := syncManagedFiles(outputs, generatedSourceMarker, false); err != nil {
		return err
	}
	if err := cleanGeneratedTree(routeTree, outputs, true, false); err != nil {
		return err
	}
	if err := cleanGeneratedTree(apiTree, outputs, false, false); err != nil {
		return err
	}
	if err := syncManagedFiles(moduleOutputs, generatedModuleMarker, false); err != nil {
		return err
	}
	if err := cleanManagedModules(filepath.Join(root, "app"), moduleOutputs, false); err != nil {
		return err
	}
	return cleanLegacyGeneratedRoot(filepath.Join(root, "server", "internal", "gobeyondgen"), check)
}

func projectedSource(root, authorFile string, content []byte) ([]byte, error) {
	relative, err := filepath.Rel(root, authorFile)
	if err != nil {
		return nil, err
	}
	var generated bytes.Buffer
	generated.WriteString(generatedSourceMarker)
	generated.WriteString("\n//line ")
	generated.WriteString(filepath.ToSlash(relative))
	generated.WriteString(":1\n")
	generated.Write(content)
	if len(content) == 0 || content[len(content)-1] != '\n' {
		generated.WriteByte('\n')
	}
	return generated.Bytes(), nil
}

func parseRouteSource(root, file string, content []byte, websiteImport string) (*ast.File, error) {
	files := token.NewFileSet()
	parsed, err := parser.ParseFile(files, file, content, parser.ImportsOnly|parser.ParseComments|parser.AllErrors)
	if err != nil {
		return nil, err
	}
	for _, imported := range parsed.Imports {
		importPath, unquoteErr := strconv.Unquote(imported.Path.Value)
		if unquoteErr != nil {
			return nil, fmt.Errorf("%s: invalid import %s", authorPath(root, file), imported.Path.Value)
		}
		if importPath == websiteImport+"/app" || strings.HasPrefix(importPath, websiteImport+"/app/") ||
			strings.HasPrefix(importPath, websiteImport+"/internal/gobeyondgen/routes/") {
			position := files.Position(imported.Path.Pos())
			return nil, fmt.Errorf("%s:%d:%d imports route-owned package %q; share ordinary Go code outside app/ instead of importing one route from another", authorPath(root, file), position.Line, position.Column, importPath)
		}
	}
	return parsed, nil
}

func authorPath(root, file string) string {
	relative, err := filepath.Rel(root, file)
	if err != nil {
		return filepath.ToSlash(file)
	}
	return filepath.ToSlash(relative)
}

func routeModule(moduleRoot, modulePath, websiteImport, goVersion, routeDir, key string) ([]byte, error) {
	replacement, err := filepath.Rel(routeDir, moduleRoot)
	if err != nil {
		return nil, err
	}
	content := generatedModuleMarker + "\n" +
		"module " + path.Join(websiteImport, "internal/gobeyondroute", key) + "\n\n" +
		"go " + goVersion + "\n\n" +
		"require " + modulePath + " " + moduleRequireVersion(modulePath) + "\n\n" +
		"replace " + modulePath + " => " + strconv.Quote(filepath.ToSlash(replacement)) + "\n"
	localReplacements, err := routeLocalReplacements(moduleRoot, modulePath, routeDir)
	if err != nil {
		return nil, err
	}
	for _, localReplacement := range localReplacements {
		content += localReplacement + "\n"
	}
	return []byte(content), nil
}

// routeLocalReplacements copies local replace directives from the website
// module into each generated route module. Go deliberately does not propagate
// replace directives through dependencies, so without this an unreleased local
// GoBeyond checkout (or another local module used directly by page.go) becomes
// unavailable as soon as route tooling regenerates the sidecar go.mod.
func routeLocalReplacements(moduleRoot, modulePath, routeDir string) ([]string, error) {
	data, err := os.ReadFile(filepath.Join(moduleRoot, "go.mod"))
	if err != nil {
		return nil, err
	}
	inBlock := false
	var replacements []string
	for _, original := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(strings.SplitN(original, "//", 2)[0])
		if line == "" {
			continue
		}
		if line == "replace (" {
			inBlock = true
			continue
		}
		if inBlock && line == ")" {
			inBlock = false
			continue
		}
		if !inBlock {
			if !strings.HasPrefix(line, "replace ") {
				continue
			}
			line = strings.TrimSpace(strings.TrimPrefix(line, "replace "))
		}
		fields := strings.Fields(line)
		arrow := -1
		for index, field := range fields {
			if field == "=>" {
				arrow = index
				break
			}
		}
		if arrow < 1 || arrow+2 != len(fields) || fields[0] == modulePath {
			continue
		}
		target, unquoteErr := strconv.Unquote(fields[arrow+1])
		if unquoteErr != nil {
			target = fields[arrow+1]
		}
		if !filepath.IsAbs(target) && target != "." && !strings.HasPrefix(target, "./") && !strings.HasPrefix(target, "../") {
			continue
		}
		if !filepath.IsAbs(target) {
			target = filepath.Join(moduleRoot, filepath.FromSlash(target))
		}
		relative, relErr := filepath.Rel(routeDir, target)
		if relErr != nil {
			return nil, relErr
		}
		left := strings.Join(fields[:arrow], " ")
		replacements = append(replacements, "replace "+left+" => "+strconv.Quote(filepath.ToSlash(relative)))
	}
	sort.Strings(replacements)
	return replacements, nil
}

func moduleRequireVersion(modulePath string) string {
	base := path.Base(modulePath)
	if len(base) > 1 && base[0] == 'v' {
		if major, err := strconv.Atoi(base[1:]); err == nil && major >= 2 {
			return fmt.Sprintf("v%d.0.0", major)
		}
	}
	return "v0.0.0"
}

func findModule(start string) (root, modulePath, goVersion string, err error) {
	current := filepath.Clean(start)
	for {
		data, readErr := os.ReadFile(filepath.Join(current, "go.mod"))
		if readErr == nil {
			for _, line := range strings.Split(string(data), "\n") {
				fields := strings.Fields(line)
				if len(fields) == 2 {
					switch fields[0] {
					case "module":
						modulePath = fields[1]
					case "go":
						goVersion = fields[1]
					}
				}
			}
			if modulePath == "" || goVersion == "" {
				return "", "", "", fmt.Errorf("%s must declare module and go directives", filepath.Join(current, "go.mod"))
			}
			return current, modulePath, goVersion, nil
		}
		if !errors.Is(readErr, os.ErrNotExist) {
			return "", "", "", readErr
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", "", "", errors.New("could not find the website Go module")
		}
		current = parent
	}
}

func syncManagedFiles(files map[string][]byte, marker string, check bool) error {
	paths := make([]string, 0, len(files))
	for file := range files {
		paths = append(paths, file)
	}
	sort.Strings(paths)
	for _, file := range paths {
		expected := files[file]
		existing, err := os.ReadFile(file)
		if err == nil && bytes.Equal(existing, expected) {
			continue
		}
		if check {
			return fmt.Errorf("generated output is stale: %s", file)
		}
		if err == nil && !bytes.HasPrefix(existing, []byte(marker)) {
			return fmt.Errorf("refusing to overwrite user-owned generated target %s", file)
		}
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(file, expected, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func cleanGeneratedTree(root string, expected map[string][]byte, preserveRootFiles, check bool) error {
	var directories []string
	err := filepath.WalkDir(root, func(file string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			if errors.Is(walkErr, os.ErrNotExist) {
				return nil
			}
			return walkErr
		}
		if entry.IsDir() {
			directories = append(directories, file)
			return nil
		}
		if _, ok := expected[filepath.Clean(file)]; ok {
			return nil
		}
		if preserveRootFiles && filepath.Dir(file) == root {
			return nil
		}
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		if !bytes.HasPrefix(content, []byte(generatedSourceMarker)) {
			return fmt.Errorf("unexpected user-owned file in generated route tree: %s", file)
		}
		if check {
			return fmt.Errorf("orphaned generated output is stale: %s", file)
		}
		return os.Remove(file)
	})
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	sort.Slice(directories, func(i, j int) bool { return len(directories[i]) > len(directories[j]) })
	for _, directory := range directories {
		if directory != root {
			_ = os.Remove(directory)
		}
	}
	return nil
}

func cleanManagedModules(appRoot string, expected map[string][]byte, check bool) error {
	return filepath.WalkDir(appRoot, func(file string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			if errors.Is(walkErr, os.ErrNotExist) {
				return nil
			}
			return walkErr
		}
		if entry.IsDir() || entry.Name() != "go.mod" {
			return nil
		}
		if _, ok := expected[filepath.Clean(file)]; ok {
			return nil
		}
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		if !bytes.HasPrefix(content, []byte(generatedModuleMarker)) {
			return nil
		}
		if check {
			return fmt.Errorf("orphaned generated route module is stale: %s", file)
		}
		return os.Remove(file)
	})
}

func cleanLegacyGeneratedRoot(root string, check bool) error {
	var directories []string
	err := filepath.WalkDir(root, func(file string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			if errors.Is(walkErr, os.ErrNotExist) {
				return nil
			}
			return walkErr
		}
		if entry.IsDir() {
			directories = append(directories, file)
			return nil
		}
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		if !bytes.HasPrefix(content, []byte("// Code generated by ")) {
			return fmt.Errorf("legacy generated root contains user-owned file %s; move it before regenerating", file)
		}
		if check {
			return fmt.Errorf("legacy generated output is stale: %s", file)
		}
		return os.Remove(file)
	})
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	sort.Slice(directories, func(i, j int) bool { return len(directories[i]) > len(directories[j]) })
	for _, directory := range directories {
		_ = os.Remove(directory)
	}
	return nil
}
