package project

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const generatedSourceMarker = "// Code generated by gobeyond route projection; DO NOT EDIT."
const generatedModuleMarker = "// Code generated by gobeyond route tooling; DO NOT EDIT."
const gobeyondModulePath = "github.com/Origens-Dev/gobeyond"

// SyncGoSources projects route-owned Go into import-safe generated packages.
// Authored app directories remain editor inputs and are never imported by the
// production server.
func SyncGoSources(root string, routes []Route, check bool) error {
	// Callers that project sources outside Write do not have the finalized
	// build identity. Use the full source fingerprint as a conservative fallback
	// so generated AI registrations still cannot silently drift.
	buildID, err := BuildID(root, routes)
	if err != nil {
		return err
	}
	return syncGoSources(root, routes, buildID, check)
}

func syncGoSources(root string, routes []Route, buildID string, check bool) error {
	if _, err := DiscoverMiddlewareSource(root); err != nil {
		return err
	}
	moduleRoot, modulePath, goVersion, err := findModule(root)
	if err != nil {
		return err
	}
	outputs := make(map[string][]byte)
	moduleOutputs := make(map[string][]byte)
	generatedRoot := filepath.Join(root, GeneratedDir)
	routeTree := filepath.Join(generatedRoot, "routes")
	apiTree := filepath.Join(generatedRoot, "api")
	workflowTree := filepath.Join(generatedRoot, "workflows")
	agentTree := filepath.Join(generatedRoot, "agents")
	cmdTree := filepath.Join(generatedRoot, "cmd")
	registryTree := filepath.Join(generatedRoot, "registry")

	websiteRelative, err := filepath.Rel(moduleRoot, root)
	if err != nil || websiteRelative == ".." || strings.HasPrefix(websiteRelative, ".."+string(filepath.Separator)) {
		return errors.New("website root must be inside the Go module root")
	}
	websiteImport := modulePath
	if websiteRelative != "." {
		websiteImport = path.Join(modulePath, filepath.ToSlash(websiteRelative))
	}
	for _, route := range routes {
		authorDir := filepath.Dir(filepath.FromSlash(route.PageFile))
		moduleFile := filepath.Join(authorDir, "go.mod")
		moduleOutputs[moduleFile], err = routeModule(moduleRoot, modulePath, websiteImport, goVersion, authorDir, route.ID)
		if err != nil {
			return err
		}
		packageName := ""
		for _, name := range []string{"page.go", "actions.go"} {
			authorFile := filepath.Join(authorDir, name)
			content, readErr := os.ReadFile(authorFile)
			if errors.Is(readErr, os.ErrNotExist) {
				continue
			}
			if readErr != nil {
				return readErr
			}
			content, err = migrateAuthorGeneratedImports(root, authorFile, content, check)
			if err != nil {
				return err
			}
			parsed, parseErr := parseRouteSource(root, authorFile, content, websiteImport)
			if parseErr != nil {
				return parseErr
			}
			if packageName != "" && packageName != parsed.Name.Name {
				return fmt.Errorf("route %s mixes Go packages %q and %q; page.go and actions.go must share one package", route.Pattern, packageName, parsed.Name.Name)
			}
			packageName = parsed.Name.Name
			target := filepath.Join(routeTree, route.ID, name)
			if name == "page.go" {
				if contractImport, found, findErr := findRouteContract(root, websiteImport, route.ID); findErr != nil {
					err = findErr
				} else if found {
					outputs[target], err = projectedPageSource(root, authorFile, content, contractImport)
				} else {
					outputs[target], err = projectedSource(root, authorFile, content)
				}
			} else {
				outputs[target], err = projectedSource(root, authorFile, content)
			}
			if err != nil {
				return err
			}
		}
	}

	apiRoot := filepath.Join(root, "app", "api")
	err = filepath.WalkDir(apiRoot, func(file string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			if errors.Is(walkErr, os.ErrNotExist) {
				return nil
			}
			return walkErr
		}
		if entry.IsDir() || entry.Name() != "route.go" {
			return nil
		}
		authorDir := filepath.Dir(file)
		relative, relErr := filepath.Rel(apiRoot, authorDir)
		if relErr != nil {
			return relErr
		}
		key := APIKey(relative)
		moduleFile := filepath.Join(authorDir, "go.mod")
		moduleOutputs[moduleFile], relErr = routeModule(moduleRoot, modulePath, websiteImport, goVersion, authorDir, key)
		if relErr != nil {
			return relErr
		}
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		content, relErr = migrateAuthorGeneratedImports(root, file, content, check)
		if relErr != nil {
			return relErr
		}
		if _, parseErr := parseRouteSource(root, file, content, websiteImport); parseErr != nil {
			return parseErr
		}
		outputs[filepath.Join(apiTree, key, "route.go")], relErr = projectedSource(root, file, content)
		return relErr
	})
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}

	workflowDefinitions, err := DiscoverWorkflowDefinitions(root)
	if err != nil {
		return err
	}
	for _, definition := range workflowDefinitions {
		authorDir := filepath.Join(root, filepath.FromSlash(definition.SourceDir))
		moduleFile := filepath.Join(authorDir, "go.mod")
		moduleOutputs[moduleFile], err = routeModule(moduleRoot, modulePath, websiteImport, goVersion, authorDir, definition.Key)
		if err != nil {
			return err
		}
		for _, relativeFile := range definition.SourceFiles {
			authorFile := filepath.Join(root, filepath.FromSlash(relativeFile))
			content, readErr := os.ReadFile(authorFile)
			if readErr != nil {
				return readErr
			}
			content, err = migrateAuthorGeneratedImports(root, authorFile, content, check)
			if err != nil {
				return err
			}
			if _, parseErr := parseRouteSource(root, authorFile, content, websiteImport); parseErr != nil {
				return parseErr
			}
			outputs[filepath.Join(workflowTree, definition.Key, filepath.Base(authorFile))], err = projectedSource(root, authorFile, content)
			if err != nil {
				return err
			}
		}
		registration, registrationErr := generatedWorkflowRegistration(definition)
		if registrationErr != nil {
			return registrationErr
		}
		outputs[filepath.Join(workflowTree, definition.Key, "gobeyond_register_gen.go")] = registration
	}
	if len(workflowDefinitions) > 0 {
		references, referencesErr := generatedWorkflowReferences(workflowDefinitions)
		if referencesErr != nil {
			return referencesErr
		}
		outputs[filepath.Join(workflowTree, "references", "references_gen.go")] = references
	}
	agentDefinitions, err := DiscoverAgentDefinitions(root)
	if err != nil {
		return err
	}
	setAIAgentRevisions(agentDefinitions, buildID)
	for _, definition := range agentDefinitions {
		authorDir := filepath.Join(root, filepath.FromSlash(definition.SourceDir))
		moduleFile := filepath.Join(authorDir, "go.mod")
		moduleOutputs[moduleFile], err = routeModule(moduleRoot, modulePath, websiteImport, goVersion, authorDir, definition.Key)
		if err != nil {
			return err
		}
		for _, relativeFile := range definition.SourceFiles {
			authorFile := filepath.Join(root, filepath.FromSlash(relativeFile))
			content, readErr := os.ReadFile(authorFile)
			if readErr != nil {
				return readErr
			}
			content, err = migrateAuthorGeneratedImports(root, authorFile, content, check)
			if err != nil {
				return err
			}
			if _, parseErr := parseRouteSource(root, authorFile, content, websiteImport); parseErr != nil {
				return parseErr
			}
			outputs[filepath.Join(agentTree, definition.Key, filepath.Base(authorFile))], err = projectedSource(root, authorFile, content)
			if err != nil {
				return err
			}
		}
		registration, registrationErr := generatedAgentRegistration(definition)
		if registrationErr != nil {
			return registrationErr
		}
		outputs[filepath.Join(agentTree, definition.Key, "gobeyond_register_gen.go")] = registration
	}
	for _, queue := range GroupWorkerQueues(workflowDefinitions, agentDefinitions) {
		mainSource, mainErr := generatedWorkflowMain(websiteImport, queue)
		if mainErr != nil {
			return mainErr
		}
		outputs[filepath.Join(cmdTree, "workflows", queue.ID, "main.go")] = mainSource
	}

	siteOutputs, err := generateSiteArtifacts(root, websiteImport, routes)
	if err != nil {
		return err
	}
	for file, content := range siteOutputs {
		outputs[file] = content
	}

	// Projections and route-local modules are ignored, ephemeral build/tooling
	// inputs. Even --check must materialize them in a clean clone before the
	// committed registry and contracts are checked.
	if err := syncManagedFiles(outputs, generatedSourceMarker, false); err != nil {
		return err
	}
	if err := cleanGeneratedTree(routeTree, outputs, true, false); err != nil {
		return err
	}
	if err := cleanGeneratedTree(apiTree, outputs, false, false); err != nil {
		return err
	}
	if err := cleanGeneratedTree(workflowTree, outputs, false, false); err != nil {
		return err
	}
	if err := cleanGeneratedTree(agentTree, outputs, false, false); err != nil {
		return err
	}
	// Generated workers/ was the pre-workflows authoring projection. It is not
	// a deployment ABI and can be removed safely after the hard source migration.
	if err := cleanGeneratedTree(filepath.Join(generatedRoot, "workers"), outputs, false, false); err != nil {
		return err
	}
	if err := cleanGeneratedTree(registryTree, outputs, false, false); err != nil {
		return err
	}
	if err := cleanGeneratedTree(cmdTree, outputs, false, false); err != nil {
		return err
	}
	if err := syncManagedFiles(moduleOutputs, generatedModuleMarker, false); err != nil {
		return err
	}
	if err := cleanManagedModules(filepath.Join(root, "app"), moduleOutputs, false); err != nil {
		return err
	}
	if err := cleanManagedModules(filepath.Join(root, "workflows"), moduleOutputs, false); err != nil {
		return err
	}
	if err := cleanManagedModules(filepath.Join(root, "agents"), moduleOutputs, false); err != nil {
		return err
	}
	for _, rel := range []string{
		filepath.Join("server", "internal", "gobeyondgen"),
		LegacyGeneratedDir,
		legacyDottedGeneratedDir,
	} {
		if err := cleanLegacyGeneratedRoot(filepath.Join(root, rel), check); err != nil {
			return err
		}
	}
	return nil
}

func rewriteLegacyGeneratedImportPaths(content []byte) []byte {
	// Go cannot treat directories named ".generated" as normal packages.
	replacements := [][2]string{
		{"/.generated/", "/" + GeneratedDir + "/"},
		{"/server/internal/gobeyondgen/", "/" + GeneratedDir + "/"},
		{"/internal/gobeyondgen/", "/" + GeneratedDir + "/"},
	}
	for _, pair := range replacements {
		content = bytes.ReplaceAll(content, []byte(pair[0]), []byte(pair[1]))
	}
	return content
}

func migrateAuthorGeneratedImports(root, authorFile string, content []byte, check bool) ([]byte, error) {
	rewritten := rewriteLegacyGeneratedImportPaths(content)
	if bytes.Equal(rewritten, content) {
		return content, nil
	}
	if check {
		return nil, fmt.Errorf("%s: legacy generated import paths are stale; run gobeyond generate", authorPath(root, authorFile))
	}
	if err := os.WriteFile(authorFile, rewritten, 0o644); err != nil {
		return nil, err
	}
	return rewritten, nil
}

func projectedSource(root, authorFile string, content []byte) ([]byte, error) {
	relative, err := filepath.Rel(root, authorFile)
	if err != nil {
		return nil, err
	}
	content = rewriteLegacyGeneratedImportPaths(content)
	var generated bytes.Buffer
	generated.WriteString(generatedSourceMarker)
	generated.WriteString("\n//line ")
	generated.WriteString(filepath.ToSlash(relative))
	generated.WriteString(":1\n")
	generated.Write(content)
	if len(content) == 0 || content[len(content)-1] != '\n' {
		generated.WriteByte('\n')
	}
	return generated.Bytes(), nil
}

// projectedPageSource keeps Props application-owned in app/page.go while
// making the generated projection use the route's canonical generated
// contract type. That makes an authored loader ergonomic without leaking a
// generated import into it, and keeps runtime/cache values contract-typed.
func projectedPageSource(root, authorFile string, content []byte, contractImport string) ([]byte, error) {
	files := token.NewFileSet()
	parsed, err := parser.ParseFile(files, authorFile, content, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	if !removePropsDeclaration(parsed) {
		return nil, fmt.Errorf("%s must declare type Props struct { ... }", authorPath(root, authorFile))
	}
	contract := &ast.GenDecl{Tok: token.IMPORT, Specs: []ast.Spec{&ast.ImportSpec{Name: ast.NewIdent("contracts"), Path: &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(contractImport)}}}}
	alias := &ast.GenDecl{Tok: token.TYPE, Specs: []ast.Spec{&ast.TypeSpec{Name: ast.NewIdent("Props"), Assign: token.Pos(1), Type: &ast.SelectorExpr{X: ast.NewIdent("contracts"), Sel: ast.NewIdent("Props")}}}}
	parsed.Decls = append([]ast.Decl{contract}, parsed.Decls...)
	parsed.Decls = append(parsed.Decls, alias)
	var formatted bytes.Buffer
	if err := format.Node(&formatted, files, parsed); err != nil {
		return nil, err
	}
	return projectedSource(root, authorFile, formatted.Bytes())
}

func removePropsDeclaration(file *ast.File) bool {
	for index, declaration := range file.Decls {
		generic, ok := declaration.(*ast.GenDecl)
		if !ok || generic.Tok != token.TYPE {
			continue
		}
		for specIndex, spec := range generic.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != "Props" {
				continue
			}
			if len(generic.Specs) == 1 {
				file.Decls = append(file.Decls[:index], file.Decls[index+1:]...)
			} else {
				generic.Specs = append(generic.Specs[:specIndex], generic.Specs[specIndex+1:]...)
			}
			return true
		}
	}
	return false
}

func parseRouteSource(root, file string, content []byte, websiteImport string) (*ast.File, error) {
	files := token.NewFileSet()
	parsed, err := parser.ParseFile(files, file, content, parser.ImportsOnly|parser.ParseComments|parser.AllErrors)
	if err != nil {
		return nil, err
	}
	for _, imported := range parsed.Imports {
		importPath, unquoteErr := strconv.Unquote(imported.Path.Value)
		if unquoteErr != nil {
			return nil, fmt.Errorf("%s: invalid import %s", authorPath(root, file), imported.Path.Value)
		}
		generatedWorkflowImport := websiteImport + "/" + GeneratedDir + "/workflows/"
		importsGeneratedWorkflowDefinition := strings.HasPrefix(importPath, generatedWorkflowImport) && importPath != generatedWorkflowImport+"references"
		if importPath == websiteImport+"/app" || strings.HasPrefix(importPath, websiteImport+"/app/") ||
			strings.HasPrefix(importPath, websiteImport+"/workflows/") || importPath == websiteImport+"/workflows" ||
			strings.HasPrefix(importPath, websiteImport+"/agents/") || importPath == websiteImport+"/agents" ||
			strings.HasPrefix(importPath, websiteImport+"/"+GeneratedDir+"/routes/") ||
			importsGeneratedWorkflowDefinition ||
			strings.HasPrefix(importPath, websiteImport+"/"+GeneratedDir+"/agents/") ||
			strings.HasPrefix(importPath, websiteImport+"/internal/gobeyondgen/routes/") ||
			strings.HasPrefix(importPath, websiteImport+"/internal/gobeyondgen/workflows/") ||
			strings.HasPrefix(importPath, websiteImport+"/internal/gobeyondgen/agents/") {
			position := files.Position(imported.Path.Pos())
			return nil, fmt.Errorf("%s:%d:%d imports framework-owned package %q; share ordinary Go code under internal/ and use generated workflow references instead of importing app/ or workflows/ packages", authorPath(root, file), position.Line, position.Column, importPath)
		}
	}
	return parsed, nil
}

func authorPath(root, file string) string {
	relative, err := filepath.Rel(root, file)
	if err != nil {
		return filepath.ToSlash(file)
	}
	return filepath.ToSlash(relative)
}

func routeModule(moduleRoot, modulePath, websiteImport, goVersion, routeDir, key string) ([]byte, error) {
	replacement, err := filepath.Rel(routeDir, moduleRoot)
	if err != nil {
		return nil, err
	}
	requires := []string{"require " + modulePath + " " + moduleRequireVersion(modulePath)}
	if modulePath != gobeyondModulePath {
		requires = append(requires, "require "+gobeyondModulePath+" v0.0.0")
	}
	content := generatedModuleMarker + "\n" +
		"module " + path.Join(websiteImport, "internal/gobeyondroute", key) + "\n\n" +
		"go " + goVersion + "\n\n" +
		strings.Join(requires, "\n") + "\n\n" +
		"replace " + modulePath + " => " + strconv.Quote(filepath.ToSlash(replacement)) + "\n"
	localReplacements, err := routeLocalReplacements(moduleRoot, modulePath, routeDir)
	if err != nil {
		return nil, err
	}
	for _, localReplacement := range localReplacements {
		content += localReplacement + "\n"
	}
	return []byte(content), nil
}

// routeLocalReplacements copies local replace directives from the website
// module into each generated route module. Go deliberately does not propagate
// replace directives through dependencies, so without this an unreleased local
// GoBeyond checkout (or another local module used directly by page.go) becomes
// unavailable as soon as route tooling regenerates the sidecar go.mod.
func routeLocalReplacements(moduleRoot, modulePath, routeDir string) ([]string, error) {
	data, err := os.ReadFile(filepath.Join(moduleRoot, "go.mod"))
	if err != nil {
		return nil, err
	}
	inBlock := false
	var replacements []string
	for _, original := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(strings.SplitN(original, "//", 2)[0])
		if line == "" {
			continue
		}
		if line == "replace (" {
			inBlock = true
			continue
		}
		if inBlock && line == ")" {
			inBlock = false
			continue
		}
		if !inBlock {
			if !strings.HasPrefix(line, "replace ") {
				continue
			}
			line = strings.TrimSpace(strings.TrimPrefix(line, "replace "))
		}
		fields := strings.Fields(line)
		arrow := -1
		for index, field := range fields {
			if field == "=>" {
				arrow = index
				break
			}
		}
		if arrow < 1 || arrow+2 != len(fields) || fields[0] == modulePath {
			continue
		}
		target, unquoteErr := strconv.Unquote(fields[arrow+1])
		if unquoteErr != nil {
			target = fields[arrow+1]
		}
		if !filepath.IsAbs(target) && target != "." && !strings.HasPrefix(target, "./") && !strings.HasPrefix(target, "../") {
			continue
		}
		if !filepath.IsAbs(target) {
			target = filepath.Join(moduleRoot, filepath.FromSlash(target))
		}
		relative, relErr := filepath.Rel(routeDir, target)
		if relErr != nil {
			return nil, relErr
		}
		left := strings.Join(fields[:arrow], " ")
		replacements = append(replacements, "replace "+left+" => "+strconv.Quote(filepath.ToSlash(relative)))
	}
	sort.Strings(replacements)
	return replacements, nil
}

func moduleRequireVersion(modulePath string) string {
	base := path.Base(modulePath)
	if len(base) > 1 && base[0] == 'v' {
		if major, err := strconv.Atoi(base[1:]); err == nil && major >= 2 {
			return fmt.Sprintf("v%d.0.0", major)
		}
	}
	return "v0.0.0"
}

func findModule(start string) (root, modulePath, goVersion string, err error) {
	current := filepath.Clean(start)
	for {
		data, readErr := os.ReadFile(filepath.Join(current, "go.mod"))
		if readErr == nil {
			for _, line := range strings.Split(string(data), "\n") {
				fields := strings.Fields(line)
				if len(fields) == 2 {
					switch fields[0] {
					case "module":
						modulePath = fields[1]
					case "go":
						goVersion = fields[1]
					}
				}
			}
			if modulePath == "" || goVersion == "" {
				return "", "", "", fmt.Errorf("%s must declare module and go directives", filepath.Join(current, "go.mod"))
			}
			return current, modulePath, goVersion, nil
		}
		if !errors.Is(readErr, os.ErrNotExist) {
			return "", "", "", readErr
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", "", "", errors.New("could not find the website Go module")
		}
		current = parent
	}
}

func syncManagedFiles(files map[string][]byte, marker string, check bool) error {
	paths := make([]string, 0, len(files))
	for file := range files {
		paths = append(paths, file)
	}
	sort.Strings(paths)
	for _, file := range paths {
		expected := files[file]
		existing, err := os.ReadFile(file)
		if err == nil && bytes.Equal(existing, expected) {
			continue
		}
		if check {
			return fmt.Errorf("generated output is stale: %s", file)
		}
		if err == nil && !bytes.HasPrefix(existing, []byte(marker)) {
			return fmt.Errorf("refusing to overwrite user-owned generated target %s", file)
		}
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(file, expected, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func cleanGeneratedTree(root string, expected map[string][]byte, preserveRootFiles, check bool) error {
	var directories []string
	err := filepath.WalkDir(root, func(file string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			if errors.Is(walkErr, os.ErrNotExist) {
				return nil
			}
			return walkErr
		}
		if entry.IsDir() {
			directories = append(directories, file)
			return nil
		}
		if _, ok := expected[filepath.Clean(file)]; ok {
			return nil
		}
		if preserveRootFiles && filepath.Dir(file) == root {
			return nil
		}
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		if !bytes.HasPrefix(content, []byte(generatedSourceMarker)) {
			return fmt.Errorf("unexpected user-owned file in generated route tree: %s", file)
		}
		if check {
			return fmt.Errorf("orphaned generated output is stale: %s", file)
		}
		return os.Remove(file)
	})
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	sort.Slice(directories, func(i, j int) bool { return len(directories[i]) > len(directories[j]) })
	for _, directory := range directories {
		if directory != root {
			_ = os.Remove(directory)
		}
	}
	return nil
}

func cleanManagedModules(appRoot string, expected map[string][]byte, check bool) error {
	return filepath.WalkDir(appRoot, func(file string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			if errors.Is(walkErr, os.ErrNotExist) {
				return nil
			}
			return walkErr
		}
		if entry.IsDir() || entry.Name() != "go.mod" {
			return nil
		}
		if _, ok := expected[filepath.Clean(file)]; ok {
			return nil
		}
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		if !bytes.HasPrefix(content, []byte(generatedModuleMarker)) {
			return nil
		}
		if check {
			return fmt.Errorf("orphaned generated route module is stale: %s", file)
		}
		return os.Remove(file)
	})
}

func cleanLegacyGeneratedRoot(root string, check bool) error {
	var directories []string
	err := filepath.WalkDir(root, func(file string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			if errors.Is(walkErr, os.ErrNotExist) {
				return nil
			}
			return walkErr
		}
		if entry.IsDir() {
			directories = append(directories, file)
			return nil
		}
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		if !bytes.HasPrefix(content, []byte("// Code generated by ")) {
			return fmt.Errorf("legacy generated root contains user-owned file %s; move it before regenerating", file)
		}
		if check {
			return fmt.Errorf("legacy generated output is stale: %s", file)
		}
		return os.Remove(file)
	})
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	sort.Slice(directories, func(i, j int) bool { return len(directories[i]) > len(directories[j]) })
	for _, directory := range directories {
		_ = os.Remove(directory)
	}
	return nil
}
