// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_category_page_05ecbf63

const RouteID = "r_category__page_05ecbf63"

type Props struct {
	Canonical    string           `json:"canonical"`
	CurrentPage  int64            `json:"currentPage"`
	Items        []PropsItemsItem `json:"items"`
	NextHref     *string          `json:"nextHref,omitempty"`
	PreviousHref *string          `json:"previousHref,omitempty"`
}

type PropsItemsItem struct {
	Href    string `json:"href"`
	Name    string `json:"name"`
	Summary string `json:"summary"`
}
