// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_category_page_05ecbf63

import (
	"time"
)

const RouteID = "r_category__page_05ecbf63"

type Props struct {
	Canonical    string           `json:"canonical"`
	CurrentPage  int64            `json:"currentPage"`
	Items        []PropsItemsItem `json:"items"`
	NextHref     *string          `json:"nextHref"`
	PreviousHref *string          `json:"previousHref"`
}

type PropsItemsItem struct {
	Href    string `json:"href"`
	Name    string `json:"name"`
	Summary string `json:"summary"`
}

// Revalidate is how long the origin may reuse this route's computed props,
// from definePage({ revalidate }). Zero leaves the route uncached. It is not
// an HTTP directive: the edge Cache-Control stays the loader's gb.CachePolicy,
// which should be derived from this window rather than drifting from it.
const Revalidate = 0 * time.Second

// Tags are this route's invalidation handles, from definePage({ tags }).
// cache.RevalidateTag on any of them drops the route's cached props.
var Tags []string
