// Code generated by GoBeyond from page.go. DO NOT EDIT.
import { definePage, schema } from "@go-beyond/schema";

export const page = definePage({
  props: schema.object({
    availability: schema.string(),
    canonical: schema.string(),
    currency: schema.string(),
    description: schema.string(),
    image: schema.string(),
    imageAlt: schema.string(),
    name: schema.string(),
    price: schema.number(),
    priceLabel: schema.string(),
    slug: schema.string()
  }),
});
