package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// projectEnvironment loads dotenv files without mutating the gobeyond process.
// Keeping this as a child-process environment means a CLI invocation cannot
// accidentally leak values into its caller or overwrite explicitly supplied
// environment variables.
func projectEnvironment(projectRoot, mode string) ([]string, error) {
	process := make(map[string]struct{})
	for _, entry := range os.Environ() {
		key, _, _ := strings.Cut(entry, "=")
		process[key] = struct{}{}
	}
	loaded := make(map[string]string)
	// Read from lowest to highest precedence. Process values always win.
	for _, name := range []string{
		".env",
		".env." + mode,
		".env.local",
		".env." + mode + ".local",
	} {
		values, err := parseDotenvFile(filepath.Join(projectRoot, name))
		if err != nil {
			return nil, err
		}
		for key, value := range values {
			if _, exists := process[key]; !exists {
				loaded[key] = value
			}
		}
	}
	environment := append([]string{}, os.Environ()...)
	for key, value := range loaded {
		environment = append(environment, key+"="+value)
	}
	return environment, nil
}

func parseDotenvFile(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if errorsIsNotExist(err) {
		return map[string]string{}, nil
	}
	if err != nil {
		return nil, err
	}
	defer file.Close()

	values := make(map[string]string)
	scanner := bufio.NewScanner(file)
	line := 0
	for scanner.Scan() {
		line++
		key, value, ok, err := parseDotenvLine(scanner.Text())
		if err != nil {
			return nil, fmt.Errorf("parse %s:%d: %w", path, line, err)
		}
		if ok {
			values[key] = value
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return values, nil
}

func errorsIsNotExist(err error) bool {
	return err != nil && os.IsNotExist(err)
}

func parseDotenvLine(line string) (key, value string, ok bool, err error) {
	line = strings.TrimSpace(line)
	if line == "" || strings.HasPrefix(line, "#") {
		return "", "", false, nil
	}
	line = strings.TrimPrefix(line, "export ")
	key, value, ok = strings.Cut(line, "=")
	if !ok {
		return "", "", false, fmt.Errorf("expected KEY=VALUE")
	}
	key = strings.TrimSpace(key)
	if !dotenvKey(key) {
		return "", "", false, fmt.Errorf("invalid environment variable %q", key)
	}
	value = strings.TrimSpace(value)
	if len(value) >= 2 && value[0] == '\'' && value[len(value)-1] == '\'' {
		return key, value[1 : len(value)-1], true, nil
	}
	if len(value) >= 2 && value[0] == '"' && value[len(value)-1] == '"' {
		unquoted, quoteErr := strconv.Unquote(value)
		if quoteErr != nil {
			return "", "", false, quoteErr
		}
		return key, unquoted, true, nil
	}
	if comment := strings.Index(value, " #"); comment >= 0 {
		value = strings.TrimSpace(value[:comment])
	}
	return key, value, true, nil
}

func dotenvKey(key string) bool {
	if key == "" {
		return false
	}
	for index, character := range key {
		if (character >= 'A' && character <= 'Z') || (character >= 'a' && character <= 'z') || character == '_' || (index > 0 && character >= '0' && character <= '9') {
			continue
		}
		return false
	}
	return true
}

// withEnvironment applies command-owned values after dotenv values. These are
// transport settings generated by the CLI, not project configuration.
func withEnvironment(environment []string, values ...string) []string {
	return append(append([]string{}, environment...), values...)
}
