// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package add_to_cart

import (
	"encoding/json"
	gb "github.com/holbrookab/gobeyond"
	"github.com/holbrookab/gobeyond/codegen"
	gbruntime "github.com/holbrookab/gobeyond/runtime"
)

const ActionID = "add_to_cart"

type Input struct {
	Mode      InputMode `json:"mode"`
	ProductID string    `json:"productId"`
	Quantity  int64     `json:"quantity"`
}

type InputMode string

const (
	InputModeBuy     InputMode = "buy"
	InputModeReserve InputMode = "reserve"
)

type Output struct {
	Message *string      `json:"message,omitempty"` // MVP: absent and null both decode as nil.
	Saved   bool         `json:"saved"`
	Status  OutputStatus `json:"status"`
}

type OutputStatus string

const (
	OutputStatusAccepted OutputStatus = "accepted"
	OutputStatusRejected OutputStatus = "rejected"
)

var inputContract = codegen.Value{Kind: codegen.KindObject, Shape: map[string]codegen.Value{"mode": codegen.Value{Kind: codegen.KindUnion, Variants: []codegen.Value{codegen.Value{Kind: codegen.KindLiteral, Literal: "buy"}, codegen.Value{Kind: codegen.KindLiteral, Literal: "reserve"}}}, "productId": codegen.Value{Kind: codegen.KindString}, "quantity": codegen.Value{Kind: codegen.KindInteger}}}

var outputContract = codegen.Value{Kind: codegen.KindObject, Shape: map[string]codegen.Value{"message": codegen.Value{Kind: codegen.KindString, Optional: true, Nullable: true}, "saved": codegen.Value{Kind: codegen.KindBoolean}, "status": codegen.Value{Kind: codegen.KindEnum, Values: []string{"accepted", "rejected"}}}}

func DecodeInput(raw json.RawMessage) (Input, error) {
	var input Input
	if err := codegen.DecodeJSON(inputContract, raw, &input); err != nil {
		return Input{}, err
	}
	return input, nil
}

func ValidateOutput(output Output) error {
	return codegen.ValidateEncodedValue(outputContract, output)
}

func Register(handler func(*gb.ActionContext, Input) (Output, error)) gbruntime.Action {
	return gbruntime.RegisterAction(ActionID, DecodeInput, ValidateOutput, handler)
}
