// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package products_slug

import (
	"github.com/Origens-Dev/gobeyond/renderplan"
	"time"
)

const RouteID = "products_slug"

type Props struct {
	DescriptionHTML renderplan.SafeHTML `json:"descriptionHTML"`
	Product         PropsProduct        `json:"product"`
	ShowBuy         bool                `json:"showBuy"`
	Summary         *string             `json:"summary,omitempty"`
}

type PropsProduct struct {
	Available bool                       `json:"available"`
	Category  PropsProductCategory       `json:"category"`
	CreatedAt time.Time                  `json:"createdAt"`
	Features  []PropsProductFeaturesItem `json:"features"`
	Hero      []byte                     `json:"hero"`
	Name      string                     `json:"name"`
	Price     float64                    `json:"price"`
	SalePrice *float64                   `json:"salePrice"`
	Slug      string                     `json:"slug"`
}

type PropsProductCategory string

const (
	PropsProductCategoryHomeGoods PropsProductCategory = "home-goods"
	PropsProductCategoryOutdoors  PropsProductCategory = "outdoors"
)

type PropsProductFeaturesItem struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

// Revalidate is how long the origin may reuse this route's computed props,
// from definePage({ revalidate }). Zero leaves the route uncached. It is not
// an HTTP directive: the edge Cache-Control stays the loader's gb.CachePolicy,
// which should be derived from this window rather than drifting from it.
const Revalidate = 60 * time.Second

// Tags are this route's invalidation handles, from definePage({ tags }).
// cache.RevalidateTag on any of them drops the route's cached props.
var Tags = []string{"products", "product"}
