// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package products_slug

import (
	"github.com/Origens-Dev/gobeyond/renderplan"
	"time"
)

const RouteID = "products_slug"

type Props struct {
	DescriptionHTML renderplan.SafeHTML `json:"descriptionHTML"`
	Product         PropsProduct        `json:"product"`
	ShowBuy         bool                `json:"showBuy"`
	Summary         *string             `json:"summary,omitempty"`
}

type PropsProduct struct {
	Available bool                       `json:"available"`
	Category  PropsProductCategory       `json:"category"`
	CreatedAt time.Time                  `json:"createdAt"`
	Features  []PropsProductFeaturesItem `json:"features"`
	Hero      []byte                     `json:"hero"`
	Name      string                     `json:"name"`
	Price     float64                    `json:"price"`
	SalePrice *float64                   `json:"salePrice"`
	Slug      string                     `json:"slug"`
}

type PropsProductCategory string

const (
	PropsProductCategoryHomeGoods PropsProductCategory = "home-goods"
	PropsProductCategoryOutdoors  PropsProductCategory = "outdoors"
)

type PropsProductFeaturesItem struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}
