// Code generated by GoBeyond from page.go. DO NOT EDIT.
import { definePage, schema } from "@go-beyond/schema";

export const page = definePage({
  props: schema.object({
    canonical: schema.string(),
    description: schema.string(),
    hours: schema.array(schema.string()),
    locality: schema.string(),
    mapHref: schema.string(),
    name: schema.string(),
    phone: schema.string(),
    phoneHref: schema.string(),
    postalCode: schema.string(),
    region: schema.string(),
    streetAddress: schema.string()
  }),
});
