// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_account_441bb226

const RouteID = "r_account_441bb226"

type Props struct {
	DisplayName string `json:"displayName"`
}
