// Code generated by GoBeyond. DO NOT EDIT.
// Contract API: gobeyond.contract/v1alpha1

package r_fr_articles_slug_fee2939e

import (
	"time"
)

const RouteID = "r_fr_articles__slug_fee2939e"

type Props struct {
	AlternateEnglish string    `json:"alternateEnglish"`
	AlternateFrench  string    `json:"alternateFrench"`
	AuthorName       string    `json:"authorName"`
	Canonical        string    `json:"canonical"`
	Description      string    `json:"description"`
	Paragraphs       []string  `json:"paragraphs"`
	PublishedAt      time.Time `json:"publishedAt"`
	PublishedLabel   string    `json:"publishedLabel"`
	Slug             string    `json:"slug"`
	SocialImage      string    `json:"socialImage"`
	Title            string    `json:"title"`
}
