// Package operator is a synthetic, compiler-only decision-agent fixture.
// DefineDecision does not install a session adapter, and these tool handlers
// have no external effects.
package operator

import (
	"context"
	gbagents "github.com/Origens-Dev/gobeyond/agents"
	decisionv1 "github.com/Origens-Dev/gobeyond/agents/decisioncontract/v1"
)

var connectTool = gbagents.DefineTool(gbagents.ToolConfig{InputSchema: map[string]any{"type": "object",
	"properties": map[string]any{"candidate_id": map[string]any{"type": "string"}}},
	RequiresApproval: true},
	func(context.Context,
		gbagents.Actor,
		map[string]any) (string,
		error) {
		return "",
			nil
	})
var contextTool = gbagents.DefineTool(gbagents.ToolConfig{InputSchema: map[string]any{"type": "object",
	"properties": map[string]any{"candidate_id": map[string]any{"type": "string"}}}},
	func(context.Context,
		gbagents.Actor,
		map[string]any) (string,
		error) {
		return "",
			nil
	})

var Agent = gbagents.DefineDecision(gbagents.DecisionConfig{
	Config: gbagents.Config{TaskQueue: "decision",
		Durable: true,
		Public:  true},

	Tools: map[string]gbagents.AITool{"connect": connectTool,
		"operator_context": contextTool},

	RoutesDir: "routes",

	Definition: decisionv1.Definition{SchemaVersion: string("decision.graph/v1"),
		DigestInputs: decisionv1.ReleaseDigestInputs{Graph: string("6b2c5a1686b688b14754fbafbd9872c0b823ffd72176fc611d06478d7a48e12e"),
			Prompts:        string("12dac900ff9dc79f3f39dc3570d942b80fc8b99bcda7fb2ca51aacfafc539e44"),
			Bindings:       string("987ed98b1faaaf09f5705c8fa7e509c761645fa3736160c45349bbc921764989"),
			Normalization:  string("99aa5ddb19c7926c2f6411af97260252e5f45f4e3f470a20e95b47f72a1b3338"),
			Authority:      string("3634de2b0e12538906dc39e131577d75623c948a272377216b0b492301414acf"),
			Policy:         string("cdc261229b5bafc36432390c722fabfe9848b21a7f98b2c274dde6cac84ce9c9"),
			LocaleAndVoice: string("f50ab7cdb73d4f3b0eb190f663b0bbe3f679e36a7dbae37716ea6a7f04d5e66e")},
		ReleaseSHA256: string("4124de3adf17fef5930149cdd7d9d1a7c25dd807eb4010dd0b2c70a463383559"),
		Graph: decisionv1.Graph{ID: string("synthetic-operator"),
			Entry:    decisionv1.RouteID("/start"),
			Fallback: decisionv1.RouteID("/help"),
			Routes:   nil,
			Authority: decisionv1.AuthorityEnvelope{ParentManifestSHA256: string(""),
				Tools: []decisionv1.ToolGrant{decisionv1.ToolGrant{ID: string("operator_context"),
					SchemaSHA256:   string("f41e66a22ed6b10cdac5882121ff7e2026f4bdcf26e6bd648caa91ada9c3fdc0"),
					ApprovalSHA256: string("")},
					decisionv1.ToolGrant{ID: string("connect"),
						SchemaSHA256:   string("f41e66a22ed6b10cdac5882121ff7e2026f4bdcf26e6bd648caa91ada9c3fdc0"),
						ApprovalSHA256: string("9999999999999999999999999999999999999999999999999999999999999999")}},
				Services: []decisionv1.ServiceGrant{decisionv1.ServiceGrant{ID: string("jev"),
					ContractSHA256:    string("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
					UsageSchemaSHA256: string("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")}},
				Bindings: []decisionv1.BindingGrant{decisionv1.BindingGrant{ID: string("recipient_matcher"),
					ContractSHA256: string("cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc")},
					decisionv1.BindingGrant{ID: string("selected_candidate_id"),
						ContractSHA256: string("dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")}},
				Budgets: map[decisionv1.BudgetDimension]decisionv1.Bound{decisionv1.BudgetDimension("ambiguous_reprompts"): decisionv1.Bound{Value: nil,
					GateID: string("g-ambiguous-reprompts")},
					decisionv1.BudgetDimension("artifact_bytes"): decisionv1.Bound{Value: nil,
						GateID: string("g-artifact-bytes")},
					decisionv1.BudgetDimension("decision_calls"): decisionv1.Bound{Value: nil,
						GateID: string("g-decision-calls")},
					decisionv1.BudgetDimension("effect_attempts"): decisionv1.Bound{Value: nil,
						GateID: string("g-effect-attempts")},
					decisionv1.BudgetDimension("first_audio_latency_ms"): decisionv1.Bound{Value: nil,
						GateID: string("g-first-audio-latency")},
					decisionv1.BudgetDimension("first_response_latency_ms"): decisionv1.Bound{Value: nil,
						GateID: string("g-first-response-latency")},
					decisionv1.BudgetDimension("input_duration_ms"): decisionv1.Bound{Value: nil,
						GateID: string("g-input-duration")},
					decisionv1.BudgetDimension("no_input_reprompts"): decisionv1.Bound{Value: nil,
						GateID: string("g-no-input-reprompts")},
					decisionv1.BudgetDimension("no_match_reprompts"): decisionv1.Bound{Value: nil,
						GateID: string("g-no-match-reprompts")},
					decisionv1.BudgetDimension("protected_payload_ttl_seconds"): decisionv1.Bound{Value: nil,
						GateID: string("g-payload-ttl")},
					decisionv1.BudgetDimension("queued_audio_bytes"): decisionv1.Bound{Value: nil,
						GateID: string("g-queued-audio")},
					decisionv1.BudgetDimension("reprompts"): decisionv1.Bound{Value: nil,
						GateID: string("g-reprompts")},
					decisionv1.BudgetDimension("route_visits"): decisionv1.Bound{Value: nil,
						GateID: string("g-route-visits")},
					decisionv1.BudgetDimension("session_duration_ms"): decisionv1.Bound{Value: nil,
						GateID: string("g-session-duration")},
					decisionv1.BudgetDimension("session_spend_microunits"): decisionv1.Bound{Value: nil,
						GateID: string("g-session-spend")},
					decisionv1.BudgetDimension("tts_characters"): decisionv1.Bound{Value: nil,
						GateID: string("g-tts-characters")}}},
			RetryGroups: []decisionv1.RetryGroup{decisionv1.RetryGroup{ID: string("recipient_selection"),
				CounterScope:         string("logical_task"),
				CountOn:              string("retry_turn_admitted"),
				DeduplicateByEventID: true,
				MaxReprompts: decisionv1.Bound{Value: nil,
					GateID: string("g-reprompts")},
				MaxNoInputReprompts: decisionv1.Bound{Value: nil,
					GateID: string("g-no-input-reprompts")},
				MaxNoMatchReprompts: decisionv1.Bound{Value: nil,
					GateID: string("g-no-match-reprompts")},
				MaxAmbiguousReprompts: decisionv1.Bound{Value: nil,
					GateID: string("g-ambiguous-reprompts")},
				Exhausted: decisionv1.Target{Route: decisionv1.RouteID("/help"),
					Phase:    decisionv1.RoutePhase(""),
					Terminal: decisionv1.TerminalAction("")}}},
			Messages: []decisionv1.MessageFamily{decisionv1.MessageFamily{ID: string("route.2f7374617274.prompt"),
				BaseLocale:     string("en"),
				FallbackLocale: string("en"),
				Arguments: []decisionv1.MessageArgument{decisionv1.MessageArgument{Name: string("name"),
					Type: decisionv1.ArgumentType("string")}},
				Variants: nil},
				decisionv1.MessageFamily{ID: string("route.2f7374617274.prompt.choice_count"),
					BaseLocale:     string("en"),
					FallbackLocale: string("en"),
					Arguments: []decisionv1.MessageArgument{decisionv1.MessageArgument{Name: string("count"),
						Type: decisionv1.ArgumentType("number")}},
					Variants: nil},
				decisionv1.MessageFamily{ID: string("route.2f636c6172696679.prompt"),
					BaseLocale:     string("en"),
					FallbackLocale: string("en"),
					Arguments: []decisionv1.MessageArgument{decisionv1.MessageArgument{Name: string("count"),
						Type: decisionv1.ArgumentType("number")}},
					Variants: nil},
				decisionv1.MessageFamily{ID: string("route.2f636c6172696679.prompt.choice_count"),
					BaseLocale:     string("en"),
					FallbackLocale: string("en"),
					Arguments: []decisionv1.MessageArgument{decisionv1.MessageArgument{Name: string("count"),
						Type: decisionv1.ArgumentType("number")}},
					Variants: nil},
				decisionv1.MessageFamily{ID: string("route.2f68656c70.prompt.help"),
					BaseLocale:     string("en"),
					FallbackLocale: string("en"),
					Arguments:      nil,
					Variants:       nil}},
			Locale: decisionv1.LocalePolicy{BaseLocale: string("en"),
				FallbackLocale:       string("en"),
				WholeMessageFallback: true,
				EnabledLocales:       []string{string("en")},
				QualificationGateID:  string("g-locale-profile")},
			RequiredVoiceCapabilities: []decisionv1.VoiceCapabilityName{decisionv1.VoiceCapabilityName("exact_text_synthesis"),
				decisionv1.VoiceCapabilityName("final_speech_text"),
				decisionv1.VoiceCapabilityName("dtmf_input"),
				decisionv1.VoiceCapabilityName("text_input"),
				decisionv1.VoiceCapabilityName("barge_in"),
				decisionv1.VoiceCapabilityName("streaming"),
				decisionv1.VoiceCapabilityName("cancellation")},
			NormalizationRulesDigest: string("dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")},
		PolicyGates: []decisionv1.PolicyGate{decisionv1.PolicyGate{ID: string("g-session-duration"),
			Kind:             decisionv1.GateKind("session_duration_ceiling"),
			Status:           decisionv1.GateStatus("unresolved"),
			Value:            string(""),
			EvidenceRef:      string(""),
			UnresolvedReason: string("Qualification evidence and owner decision are pending."),
			OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-route-visits"),
				Kind:             decisionv1.GateKind("route_visit_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-decision-calls"),
				Kind:             decisionv1.GateKind("decision_call_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-reprompts"),
				Kind:             decisionv1.GateKind("retry_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-no-input-reprompts"),
				Kind:             decisionv1.GateKind("no_input_retry_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-input-duration"),
				Kind:             decisionv1.GateKind("input_duration_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-tts-characters"),
				Kind:             decisionv1.GateKind("tts_character_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-queued-audio"),
				Kind:             decisionv1.GateKind("queued_audio_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-artifact-bytes"),
				Kind:             decisionv1.GateKind("artifact_byte_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-effect-attempts"),
				Kind:             decisionv1.GateKind("effect_attempt_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-session-spend"),
				Kind:             decisionv1.GateKind("session_spend_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-first-audio-latency"),
				Kind:             decisionv1.GateKind("first_audio_latency_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-first-response-latency"),
				Kind:             decisionv1.GateKind("first_response_latency_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-payload-ttl"),
				Kind:             decisionv1.GateKind("protected_payload_ttl"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-wrong-recipient"),
				Kind:             decisionv1.GateKind("wrong_recipient_rate"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-clarification-rate"),
				Kind:             decisionv1.GateKind("clarification_rate"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-locale-profile"),
				Kind:             decisionv1.GateKind("qualified_locale_profile"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-voice-profile"),
				Kind:             decisionv1.GateKind("qualified_voice_profile"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-voice-fallback"),
				Kind:             decisionv1.GateKind("voice_capability_fallback"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-jev-path"),
				Kind:             decisionv1.GateKind("jev_service_path_and_usage"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-caller-authority"),
				Kind:             decisionv1.GateKind("caller_and_relationship_authority"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-dtmf"),
				Kind:             decisionv1.GateKind("dtmf_negotiation"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-prompt-retention"),
				Kind:             decisionv1.GateKind("prompt_retention_and_revocation"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-prompt-preparation"),
				Kind:             decisionv1.GateKind("prompt_preparation_policy"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-no-match-reprompts"),
				Kind:             decisionv1.GateKind("no_match_retry_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-ambiguous-reprompts"),
				Kind:             decisionv1.GateKind("ambiguity_retry_ceiling"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Qualification evidence and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-route-authoring"),
				Kind:             decisionv1.GateKind("route_authoring_and_graph_discovery"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Integration contract and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-session-adapter"),
				Kind:             decisionv1.GateKind("stateful_session_adapter_contract"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Integration contract and owner decision are pending."),
				OwnerDecision:    string("")},
			decisionv1.PolicyGate{ID: string("g-prompt-runtime-parity"),
				Kind:             decisionv1.GateKind("prompt_loader_and_icu_runtime_parity"),
				Status:           decisionv1.GateStatus("unresolved"),
				Value:            string(""),
				EvidenceRef:      string(""),
				UnresolvedReason: string("Integration contract and owner decision are pending."),
				OwnerDecision:    string("")}}},
},
	gbagents.Slots{
		Tools: []gbagents.Tool{{ID: "existing"}},

		Channels: []gbagents.Channel{{ID: "voice",
			Connector: "voice-provider"}},
	})
